project_id = "rsqzmxbwbqgdlaeffmjg"

[functions.discord-notify]
verify_jwt = false

[functions.discord-otp]
verify_jwt = false

[functions.sellauth-products]
verify_jwt = false

[functions.sellauth-checkout]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.discord-ticket]
verify_jwt = false

[functions.discord-ticket-register]
verify_jwt = false

[functions.discord-join-welcome]
verify_jwt = false